language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

services:
  - mysql

before_script:
  - mysql -e 'create database dbda_test;'
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - sudo php -S dbda.test:80 -t public/
  - phantomjs --version
  - phantomjs --webdriver=8643 &

script:
    - vendor/bin/phpunit
    - vendor/bin/behat
    - phantomjs app/tests/js/runner.js http://dbda.test/js/tests/test.html