language: php
php:
  - 5.4
  - 5.5
  - hhvm

services:
  - mysql

before_script:
  - mysql -e 'create database dbda_test;'
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - php -S dbda.test:8888 -t public/ &
  - phantomjs --version
  - phantomjs --webdriver=8643 &

script:
    - vendor/bin/phpunit -v
    - vendor/bin/behat -v -p travis
    - phantomjs app/tests/js/runner.js http://dbda.test:8888/js/tests/test.html