language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

allow_failures:
- php: hhvm

services:
  - mysql

before_script:
  - mysql --version
  - mysql -e 'create database dbda_test;'
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --dev --no-interaction --prefer-source
  - php -S dbda.test:8888 -t public &
  - phantomjs --version
  - phantomjs --webdriver=8643 &

script:
    - vendor/bin/phpunit -v
    - vendor/bin/behat -v -p travis
    - phantomjs app/tests/js/runner.js http://dbda.test:8888/js/tests/test.html

addons:
  hosts:
    - dbda.test